### ISSUE TITLE
Beneficiary email issue

### ISSUE THREAD

**Issue by efeali** [CurrencyCloud/currencycloud-php#11]
Hi there,

I have just noticed this issue recently. It seems there is an issue with saving beneficiary's email address during creating a new beneficiary. Everything is ok while we create a new temporary beneficiary object and set an email to this person object by using setEmail(). But after we save this beneficiary to currency cloud by using beneficiaries()->create() method and check this newly saved record the email address shows up as an empty string (and null while retrieving beneficiary).

I faced this issue in our app which leverages your api. On the other hand, I have also tested it by using your cook-book.php official test code, and got the same result. (Beneficiary's email address is not saved at all.)

thanks

**Comment by EAddario** [comment]
This is now fixed
