### ISSUE TITLE
Ordering search results

### ISSUE THREAD

**Issue by LanceJenkinZA** [CurrencyCloud/currencycloud-php#111]
Is it possible to order results by a specific column?

For example, the API documentation for finding conversions, https://www.currencycloud.com/developers/docs/item/find-conversions/ lets you specify the properties to order by:

![image](https://user-images.githubusercontent.com/6415805/107211141-3f34f180-6a59-11eb-8b28-384c01eb4f9e.png)

But I don't see how to achieve this with the SDK.

Thanks,
Lance

**Comment by jonathancouchman** [comment]
Results can be ordered using the [Pagination](https://github.com/CurrencyCloud/currencycloud-php/blob/master/src/Model/Pagination.php) object, for example, see the [payments/find](https://github.com/CurrencyCloud/currencycloud-php/blob/2e753ea9db1f7d5f2380ea48cdcc2377c4dbd076/src/EntryPoint/PaymentsEntryPoint.php#L207) call

However, in the example you give for conversions/find, the Pagination object is missing from the message signature, so currently these results cannot be ordered. We will look and resolving this oversight
