### ISSUE TITLE
Specifying currency when using BalancesEntryPoint::find method

### ISSUE THREAD

**Issue by LanceJenkinZA** [CurrencyCloud/currencycloud-php#117]
Good day,

Currently, there is no way to specify the currency when using the `BalancesEntryPoint::find` method:

```php
public function find(
        $amountFrom = null,
        $amountTo = null,
        $asAtDate = null,
        Pagination $pagination = null,
        $onBehalfOf = null
    ) {
```

The use case is to check if a user already has a specific currency set up on their account before attempting to create the currency.

For example
```php

$balances = $currencyCloud->balances()->find([currency => $currencyCode]);
if($balances->count() > 0){
  // user already has currency set up on their account
 ....
} else { 
  // Create a balance for the user
  $balance = $currencyCloud->balances()->retrieve($currencyCode);
}
```

Thanks

**Comment by gergelykovacs** [comment]
Hello @LanceJenkinZA ,

SDK provides functionality in `retrieve($currency, $onBehalfOf = null)` under `BalancesEntryPoint`, also please see in the API schema:

- https://github.com/CurrencyCloud/currencycloud-swagger/blob/master/src/reference.yaml

or filter if target currency is in the list of balances.

**Comment by LanceJenkinZA** [comment]
Thanks @gergelykovacs, but the `retrieve` method has side effects which I don't want - that is, it will create a new _balance_ if the balance is not already associated with the account.

I'm working with _SPARK_ accounts if that helps.

With reference to the _direct-demo_ platform;

- the page https://direct-demo.currencycloud.com/balances shows a list of balances available to the user.
- if the currency is not available in this list, let's say Danish Krone is not on the list, then 
- if I use the method `retrieve("DKK)`  Danish Krone will show up in this list.

My [XY Problem](https://en.wikipedia.org/wiki/XY_problem) is I would like to know if the user already has the currency associated with their account before I associate the currency with their account. 

That way I can show the message "You already have a $currencyCode account".

**Comment by gergelykovacs** [comment]
@LanceJenkinZA , you can use the `BalancesEntryPoint::find` (api: `/balances/find`) to see balances per currency and filter the list to the currency you are interested in (https://www.php.net/array_filter), also you can use the on-behalf-of option to perform the same search for sub-accounts. If the list does not contain the currency you are interested in you can act accordingly. Filtering an array in your code equal to what you would get with providing a specific currency code to the SDK method. SDK method and API does not provide it.

**Comment by LanceJenkinZA** [comment]
Thanks @gergelykovacs.

I see I miss-read the documentation.  When testing with Postman the query did work:

![image](https://user-images.githubusercontent.com/6415805/129273641-98e9cabc-8fa3-4d6a-8b03-9056ded93832.png)

But I see that filtering by currency is not documented.

**Comment by gergelykovacs** [comment]
Hi @LanceJenkinZA , 
I close this issue, further related documentation can be found here:

- https://developer.currencycloud.com/cookbooks/pay-a-beneficiary-using-funds-in-a-different-currency/
