### ISSUE TITLE
No implementation for the FundingEntryPoint

### ISSUE THREAD

**Issue by LanceJenkinZA** [CurrencyCloud/currencycloud-php#120]
I'm trying to locate funding account details using the following API end point: https://developer.currencycloud.com/docs/item/find-funding-accounts/

I can see the code for the end point:
https://github.com/CurrencyCloud/currencycloud-php/blob/master/src/EntryPoint/FundingEntryPoint.php

But I can't see how to use it with the SDK.

**Comment by jonathancouchman** [comment]
This is a bug. The Funding EntryPoint is missing from the client, so it is not callable. I will raise an internal ticket to get this resolved.
