### ISSUE TITLE
Funding accounts on_behalf_of

### ISSUE THREAD

**Issue by Si0n** [CurrencyCloud/currencycloud-php#124]
Greetings! 
Can you please clarify one thing: currency cloud support tells that endpoint `/funding_accounts/find` can accept `on_behalf_of` parameter, but there is no info in documentation of API nor in this SDK. 
They even added an example: `baseUrl/funding_accounts/find?payment_type=priority&currency=GBP&account_id=*-d52f-4cc9-b2e4-*&on_behalf_of=*-5020-45ac-bd6d-*`  _(i replaced real data with stars)_ 
So if API really accepts `on_behalf_of` parameter - can you please add a support for this feature in SDK?

**Comment by jonathancouchman** [comment]
You are correct that this api call supports on_behalf_of. We will add it to the swagger documentation ad update the SDKs accordingly
