### ISSUE TITLE
symfony 3.3 issues

### ISSUE THREAD

**Issue by steve-rhodes** [CurrencyCloud/currencycloud-php#14]
I use Laravel and have Symfony v3.3 dependecies installed by the framework.

`composer CurrencyCloud/currencycloud-php` is giving me an error:

- Installation request for currency-cloud/client ^0.10.0 -> satisfiable by currency-cloud/client[v0.10.0].
- Conclusion: remove symfony/event-dispatcher v3.3.12
- Conclusion: don't install symfony/event-dispatcher v3.3.12
Installation failed, reverting ./composer.json to its original content.

Is there any particular reason for this? What is your advice? I don't think Laravel lets me roll back to ^2.8

Thanks!

Steve

This is from the laravel/framework composer.json:

```
 "require": {
        "php": ">=7.0",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "doctrine/inflector": "~1.1",
        "erusev/parsedown": "~1.6",
        "league/flysystem": "~1.0",
        "monolog/monolog": "~1.12",
        "mtdowling/cron-expression": "~1.0",
        "nesbot/carbon": "~1.20",
        "psr/container": "~1.0",
        "psr/simple-cache": "^1.0",
        "ramsey/uuid": "~3.0",
        "swiftmailer/swiftmailer": "~6.0",
        "symfony/console": "~3.3",
        "symfony/debug": "~3.3",
        "symfony/finder": "~3.3",
        "symfony/http-foundation": "~3.3",
        "symfony/http-kernel": "~3.3",
        "symfony/process": "~3.3",
        "symfony/routing": "~3.3",
        "symfony/var-dumper": "~3.3",
        "tijsverkoyen/css-to-inline-styles": "~2.2",
        "vlucas/phpdotenv": "~2.2"
    },
```

**Comment by EAddario** [comment]
Fixed in v1.0.1
