### ISSUE TITLE
Wrong error structure for error_code "report_write_permission_missing"

### ISSUE THREAD

**Issue by valkars** [CurrencyCloud/currencycloud-php#147]
Tried to make request to generate payment report (https://developer.currencycloud.com/docs/item/generate-payment-report/) and received 500 error, because of invalid error structure.
Typical error structure is:
- error_code = string
- error_messages = array<field: array of errors>
error:
- code = string
- message = string
- params = array
Example: 
`{"error_code":"auth_failed","error_messages":{"username":[{"code":"invalid_supplied_credentials","message":"Authentication failed with the supplied credentials","params":[]}]}}`

But for error "report_write_permission_missing" structure is wrong:
- error_code = string
- error_messages = array<field: error>
Example:
`{"error_code":"report_write_permission_missing","error_messages":{"base":{"code":"report_write_permission_missing","message":"User does not have permission 'report_write' to perform this operation","params":[]}}}`

Which results in ClientHttpErrorListener:62 error - Cannot access offset of type string on string
`'code' => $messageContext['code'],`

**Comment by jonathancouchman** [comment]
Thank you for reporting this issue, we will investigate and update the ticket accordingly
