### ISSUE TITLE
Payment submission data retrievement

### ISSUE THREAD

**Issue by david-vde** [CurrencyCloud/currencycloud-php#16]
Hello

Regarding the doc : https://developer.currencycloud.com/documentation/api-docs/payments/get-payments-id-submission/

I can't find a way in the PHP client how to use this route, is an implementation planned in a near future for this ?

Thank you

**Comment by EAddario** [comment]
Fixed in v0.20.1

Apologies it has taken this long. It shouldn't have, but it did. We will do much better from now on.
