### ISSUE TITLE
Unable to set beneficiary address

### ISSUE THREAD

**Issue by tpyo** [CurrencyCloud/currencycloud-php#2]
Beneficiary::setBeneficiaryAddress() [requires an array value](https://github.com/CurrencyCloud/currencycloud-php/blob/c576f2e5e462dd4f96c8589227cee157e629e206/src/Model/Beneficiary.php#L644), however, this is rejected by the API:

``` php
$beneficiary->setBeneficiaryAddress(array('23 Acacia Road'));
// => API Error: Beneficiary address is missing
```

**Comment by tpyo** [comment]
It seems the beneficiary address is not set by [convertBeneficiaryToRequest()](https://github.com/CurrencyCloud/currencycloud-php/blob/master/src/EntryPoint/BeneficiariesEntryPoint.php#L130), but adding the parameter does not work: 

``` php
...
'beneficiary_address' => $beneficiary->getBeneficiaryAddress()
...
// => Invalid extra parameters:'{:beneficiary_address=>{:"0"=>"23 Acacia Road"}}'
```

**Comment by pradoshcubet** [comment]
Same issue for me too.. How do i Fix this ?

**Comment by ollieza** [comment]
Please see my pull request with fix for this bug at https://github.com/CurrencyCloud/currencycloud-php/pull/3

**Comment by ollieza** [comment]
Pull request merged. This issue can now be closed.
