### ISSUE TITLE
Authetication

### ISSUE THREAD

**Issue by lasamarndi** [CurrencyCloud/currencycloud-php#53]
How will do universal Authentication part

**Comment by EAddario** [comment]
Hi lasamarndi, not sure what you mean by universal authentication. Could you please clarify the use case, maybe with code snippet?

Just in case you haven't seen it yet, there's an example on how to authenticate in the [cook-book](https://github.com/CurrencyCloud/currencycloud-php/blob/master/examples/cook-book.php) but it generally follows the pattern below, replacing of course _user-id_ and _api-key_ with valid values

```php
$session = new Session(
    Session::ENVIRONMENT_DEMONSTRATION,
    '<user-id>',
    '<api-key>'
);
```

**Comment by EAddario** [comment]
Conversation moved to #55
