### ISSUE TITLE
Authetication

### ISSUE THREAD

**Issue by lasamarndi** [CurrencyCloud/currencycloud-php#55]
i want to login through  User Id and Password.
 like your url : https://direct-demo.currencycloud.com/login

$session = new Session(
    Session::ENVIRONMENT_DEMONSTRATION,
             '<user-id>',
               '<api-key>'
);
in this case you did user id and api key
but i want to do like direct demo through this url :  https://direct-demo.currencycloud.com/login

**Comment by EAddario** [comment]
Sorry lasamarndi but, by design, the only authentication mechanism we support on the API is Id / Key

**Comment by lasamarndi** [comment]
if i have multiple users then how will do that.

**Comment by EAddario** [comment]
Your application will need to implement the required logic to map between your user's credentials and the corresponding API keys

**Comment by lasamarndi** [comment]
thanks for response, how will implement please give me snap of code.

**Comment by EAddario** [comment]
Apologies lasamarndi but we are not able to provide support beyond our SDKs

**Comment by lasamarndi** [comment]
then i will contact cloud currency.
  i was send message through email but there also not get response
