### ISSUE TITLE
Joing

### ISSUE THREAD

**Issue by lasamarndi** [CurrencyCloud/currencycloud-php#58]
how to join Payment and Beneficiary Model.

**Comment by EAddario** [comment]
Documentation for the API and the service is available in the [Development Center](https://www.currencycloud.com/developers/overview/) and the [Cookbooks](https://www.currencycloud.com/developers/cookbooks/) section covers common use cases. For example, [Make simple payments to beneficiaries](https://www.currencycloud.com/developers/cookbooks/make-simple-payments-to-beneficiaries/) shows the relationship between the Beneficiary and the Payment models.

**Comment by lasamarndi** [comment]
yaa, but i want retrieve payments details including beneficiary details in single page.
