### ISSUE TITLE
conversion limit issue

### ISSUE THREAD

**Issue by anu403** [CurrencyCloud/currencycloud-php#61]
Is there any API to find the conversion above and conversion below limits?

**Comment by EAddario** [comment]
Hi anu403, we do not offer that facility via the API but it's available in Direct (web front-end) under Onboarding->selected Account Name->selected Contact Name->Risk Limits

Please note the limits can only be changed by our [Support team](mailto:support@currencycloud.com?subject=Increase%20Risk%20Limits)
