### ISSUE TITLE
Incorrent time for sending

### ISSUE THREAD

**Issue by fiamma06** [CurrencyCloud/currencycloud-php#65]
https://github.com/CurrencyCloud/currencycloud-php/blob/52368ffded98f3f72ff35739c202360d90061f9d/src/EntryPoint/TransactionsEntryPoint.php#L80

Server don't support full datetime format, only date format it support

**Comment by EAddario** [comment]
Hi @fiamma06, the return value signifies the settlement has occurred on the date but no specific time has been recorded. When/if downstream providers return specific settlement times  the return value will include it.
