### ISSUE TITLE
Bulk upload

### ISSUE THREAD

**Issue by lasamarndi** [CurrencyCloud/currencycloud-php#67]
i have seen bulk upload option in your could currency project (www.cloudcurrency.com) but your package dont provide this features. how will implement this feature

**Comment by EAddario** [comment]
Bulk upload is only provided in the Direct product (web interface). One way to replicate that functionality using the SDK is to parse a text file into an array mapping payment information, for example, to its corresponding JSON representation and then while iterating over the array calling the payment create endpoint.

Some .cvs format examples are available in in the [Bulk Upload (CSV Upload)](https://www.currencycloud.com/support/topics/item/bulk-upload-csv-upload/) section of our website
