### ISSUE TITLE
Fields returned in reference/beneficiary_required_details are not consistent with beneficiaries/create

### ISSUE THREAD

**Issue by niraj-shah** [CurrencyCloud/currencycloud-php#8]
There are some inconsistencies with the data that is returned by the `/v2/reference/beneficiary_required_details` API call, and what is sent in the `/v2/beneficiaries/create` API.

For example, calling `beneficiary_required_details` returns the field `acct_number` (see below), but the field is actually called `account_number` in the `beneficiaries/create` API.

```
{
  "details": [
    {
      "payment_type": "priority",
      "acct_number": "^\\d{1,17}$",
      "aba": "^[0-9A-Z]{9}$"
    },
    ...
  ]
}
```

Why the difference in field names?

Another inconsistency in the same API call is when using `GBP` as currency and `GB` as country. It's returns `sort_code` as a field, but the `beneficiaries/create` uses `routing_code_type_1` and `routing_code_value_1` for this value.

**Comment by tpyo** [comment]
This caught me too.  +1 - should be corrected.

**Comment by EAddario** [comment]
This issue is now on the API v3 backlog
