### ISSUE TITLE
event-dispatcher version conflict with Laravel

### ISSUE THREAD

**Issue by speix** [CurrencyCloud/currencycloud-php#87]
symfony/event-dispatcher version used in your package is incompatible with the latest Laravel version.

**Comment by gelinger777** [comment]
@speix  have you solved it?

**Comment by speix** [comment]
@gelinger777 I am not using the SDK at the moment.

**Comment by jonathancouchman** [comment]
Thank you for raising this issue. Sorry for the very late response. We will investigate this conflict and how to resolve by upgrading the dependencies. 

Feel free to submit proposed changes if you wish and we will review.

**Comment by gelinger777** [comment]
yes, please make sure the package is fully compatible with Laravel's latest editions...

**Comment by Si0n** [comment]
Hello, any news on this?

**Comment by markunsworth** [comment]
Ive just created a PR (#115) for this
