### ISSUE TITLE
symfony/yaml v5 supporting

### ISSUE THREAD

**Issue by Aleksanderlebedenko** [CurrencyCloud/currencycloud-php#88]
You are using symfony/yaml: ^2.7|^3.0|^4.0, but modern Symfony applications have symfony/yaml v5 version. Your dependency makes impossible to use this SDK in the modern  Symfony apps.

**Comment by jonathancouchman** [comment]
Thank you for raising this issue regarding the lack of support for the latest symfony versions. Sorry for the very late response. We will investigate upgrading the dependencies, although we always welcome contributions from the wider community, so feel free to submit any proposed fixes
