### ISSUE TITLE
Fundamental issue with APIs not accepting arrays

### ISSUE THREAD

**Issue by niraj-shah** [CurrencyCloud/currencycloud-php#9]
There is a issue with the API not being able to accept arrays correctly. I have come to this conclusion after attempting to address and fix issues #6 and #7. 

Neither of the following modification to the PHP SDK worked:

```
$common['payment_types'] = ['regular'];
$common['payment_types'] = json_encode( ['regular'] );
$common['payment_types'][] = 'regular';
```

They resulted in one of two errors:

```
{
  "error_code": "beneficiary_update_failed",
  "error_messages": {
    "payment_types": [
      {
        "code": "payment_types_type_is_wrong",
        "message": "payment_types should be of array type",
        "params": {
          "type": "array"
        }
      }
    ]
  }
}
```

or

```
{  
  "field":"base",
  "code":"invalid_extra_parameters",
  "message":"Invalid extra parameters:'{:payment_types=>{:\"1\"=>\"regular\"}}'",
  "params":{  
    "parameters":{  
      "payment_types":{  
        "0": "regular"
      }
    }
  }
}
```

This leads me to believe there is a issue with the API itself not being able to accept array data correctly. Happy to be proven wrong If someone has found a workaround or solution.

**Comment by EAddario** [comment]
Fixed in v0.17.3

Apologies it has taken this long. It shouldn't have, but it did. We will do much better from now on.
